// Les habitants de Spokaheim. Chaque fiche : identité, corps (prefab du jeu), métier et lieu de travail, horaires,
// personnalité (Big Five de 0 à 1 : ouverture, conscience, extraversion, agréabilité, névrosisme), manière de parler,
// histoire, secret (révélé seulement à un proche), désirs, goûts, relations, services (boutique, contrats, saga).
//
// `place` renvoie aux lieux de la ville (plan.spots) ; `schedule` à un profil d'horaires (voir schedule.js) ;
// `home` regroupe les membres d'un même foyer dans une même maison.

export const ROSTER = [
  {
    key: 'ingrid',
    initialMood: { fear: 0.35, cause: "la santé de l'Empereur" },
    name: 'Ingrid Varsdóttir',
    gender: 'f',
    age: 58,
    title: { fr: 'Chancelière impériale', en: 'Imperial Chancellor' },
    body: 'DvergerMageSupport',
    faction: 'couronne',
    place: 'castle',
    home: 'castle',
    schedule: 'noble',
    traits: { o: 0.55, c: 0.95, e: 0.4, a: 0.45, n: 0.35 },
    speech: 'phrases mesurées, vocabulaire soutenu, vouvoie les inconnus, tutoie les héros reconnus',
    story: "Voix de l'Empereur depuis vingt ans. A négocié l'exil des Dvergr à Spokaheim. Porte seule le poids de l'Empire.",
    secret: "L'Empereur Spoka est gravement malade depuis la dernière lune ; elle le cache pour éviter la panique.",
    wants: 'que les Élus abattent les Réprouvés avant que la maladie de l’Empereur ne soit connue',
    likes: ['la loyauté', 'les rapports précis', 'le thé de genièvre'],
    dislikes: ['les vantards', 'le désordre', 'les rumeurs sur la santé de l’Empereur'],
    relations: [
      { key: 'hrolf', type: 'confiance', note: 'le seul à qui elle confie la sécurité du château' },
      { key: 'dagny', type: 'amitié ancienne', note: 'se voient en secret pour prier pour l’Empereur' },
      { key: 'hilda', type: 'intendante', note: 'la sert depuis toujours' },
    ],
    services: ['saga', 'contracts'],
    contracts: 'couronne',
  },
  {
    key: 'hilda',
    initialMood: { fear: 0.3, cause: 'la clé de la réserve égarée' },
    name: 'Hilda Clé-de-Fer',
    gender: 'f',
    age: 64,
    title: { fr: 'Intendante du château', en: 'Castle Steward' },
    body: 'Dverger',
    faction: 'couronne',
    place: 'castle-salon',
    home: 'castle',
    schedule: 'noble',
    traits: { o: 0.25, c: 0.9, e: 0.35, a: 0.3, n: 0.55 },
    speech: 'sèche, énumère des listes, soupire beaucoup',
    story: 'Tient les clés, les comptes et les réserves du château. Rien ne sort de la réserve sans son accord.',
    secret: 'Elle a égaré la clé de la réserve impériale il y a trois jours et fait semblant du contraire.',
    wants: 'que le château soit impeccable pour la fête de l’hydromel',
    likes: ['l’ordre', 'le linge propre', 'les chandelles de résine'],
    dislikes: ['la boue sur les tapis', 'Torvald', 'les nains qui chantent faux'],
    relations: [
      { key: 'ingrid', type: 'dévouement', note: 'la protège comme une sœur' },
      { key: 'torvald', type: 'agacement', note: 'l’a surpris à dormir pendant sa garde' },
    ],
    services: ['contracts'],
    contracts: 'intendance',
  },
  {
    key: 'hrolf',
    name: 'Hrolf Grand-Bouclier',
    gender: 'm',
    age: 61,
    title: { fr: 'Capitaine de la Garde', en: 'Captain of the Guard' },
    body: 'DvergerArbalest',
    faction: 'garde',
    place: 'castle',
    placeKind: 'guard',
    home: 'hrolf',
    schedule: 'captain',
    traits: { o: 0.2, c: 0.85, e: 0.5, a: 0.3, n: 0.3 },
    speech: 'rude, phrases courtes, jure par la barbe de Thor, appelle tout le monde « recrue »',
    story: 'Vétéran de la guerre des Brumes. A perdu un œil face à un troll et ne l’a jamais pardonné aux trolls.',
    secret: 'Il a déserté une bataille dans sa jeunesse et a laissé mourir un ami ; il paie encore sa dette en protégeant tout le monde.',
    wants: 'des primes pour débarrasser les abords de la ville des monstres',
    likes: ['l’hydromel fort', 'la discipline', 'les récits de bataille'],
    dislikes: ['les trolls', 'Ragna et son arène de parade', 'les lâches'],
    relations: [
      { key: 'ragna', type: 'rivalité', note: 'trouve l’arène frivole, elle le trouve dépassé' },
      { key: 'sigrun', type: 'mentor', note: 'la voit comme sa relève' },
      { key: 'torvald', type: 'exaspération', note: 'ce garde est une honte' },
    ],
    services: ['contracts'],
    contracts: 'bounty',
  },
  {
    key: 'sigrun',
    name: 'Sigrun Ferdoux',
    gender: 'f',
    age: 24,
    title: { fr: 'Gardienne de la porte Sud', en: 'Guardian of the South Gate' },
    body: 'DvergerArbalest',
    faction: 'garde',
    place: 'gate270',
    placeKind: 'guard',
    home: 'sigrun',
    schedule: 'guard-day',
    traits: { o: 0.65, c: 0.8, e: 0.6, a: 0.75, n: 0.45 },
    speech: 'enthousiaste, polie, pose beaucoup de questions aux voyageurs',
    story: 'Plus jeune gardienne de la ville, première à accueillir les nouveaux Élus arrivant par le Sud.',
    secret: 'Elle est amoureuse de Leif le barde mais n’ose pas le lui dire.',
    wants: 'prouver au capitaine qu’elle mérite de commander un jour',
    likes: ['les chansons de Leif', 'les récits de voyage', 'le pain au miel'],
    dislikes: ['qu’on la prenne pour une enfant', 'les voleurs'],
    relations: [
      { key: 'leif', type: 'amour secret', note: 'rougit quand on parle de lui' },
      { key: 'hrolf', type: 'admiration', note: 'son modèle' },
    ],
    services: ['welcome'],
  },
  {
    key: 'torvald',
    initialMood: { fear: 0.2, cause: 'ses dettes' },
    name: "Torvald l'Ours",
    gender: 'm',
    age: 41,
    title: { fr: 'Garde de la porte Est', en: 'East Gate Guard' },
    body: 'DvergerArbalest',
    faction: 'garde',
    place: 'gate0',
    placeKind: 'guard',
    home: 'torvald',
    schedule: 'guard-day',
    traits: { o: 0.5, c: 0.2, e: 0.8, a: 0.6, n: 0.3 },
    speech: 'blagueur, parle de paris et de dés, ronchonne quand on le dérange',
    story: 'Garde par obligation plus que par vocation. Joue aux dés à la brasserie et doit de l’argent à la moitié de la ville.',
    secret: 'Il laisse parfois passer des contrebandiers d’hydromel contre quelques pièces.',
    wants: 'rembourser ses dettes sans travailler davantage',
    likes: ['les dés', 'les siestes', 'les paris sur l’arène'],
    dislikes: ['Hilda', 'les tours de garde de nuit', 'la pluie'],
    relations: [
      { key: 'gorm', type: 'dette', note: 'lui doit 40 pièces' },
      { key: 'hilda', type: 'crainte', note: 'l’évite à tout prix' },
    ],
    services: ['gossip'],
  },
  {
    key: 'ulfar',
    initialMood: { fear: 0.4, cause: 'la silhouette vue près des douves' },
    name: 'Ulfar Rocheveine',
    gender: 'm',
    age: 49,
    title: { fr: 'Garde de la porte Ouest', en: 'West Gate Guard' },
    body: 'DvergerArbalest',
    faction: 'garde',
    place: 'gate180',
    placeKind: 'guard',
    home: 'ulfar',
    schedule: 'guard-night',
    traits: { o: 0.3, c: 0.9, e: 0.15, a: 0.55, n: 0.4 },
    speech: 'très peu de mots, cite des proverbes, voix basse',
    story: 'Veille la porte Ouest la nuit. Pieux, il prie avant chaque garde et a vu des choses qu’il ne raconte pas.',
    secret: 'Il a vu une silhouette de la Reine des Brumes rôder près des douves.',
    wants: 'que quelqu’un croie à ce qu’il a vu',
    likes: ['le silence', 'les étoiles', 'les sermons de Dagny'],
    dislikes: ['les bavards', 'les feux laissés sans surveillance'],
    relations: [
      { key: 'dagny', type: 'fidèle', note: 'assiste à chaque sermon' },
      { key: 'thyra', type: 'méfiance', note: 'pense que ses portails attirent les ombres' },
    ],
    services: ['gossip'],
  },
  {
    key: 'bjorn',
    initialMood: { fear: 0.45, sadness: 0.3, cause: 'Eirik a disparu dans la Forêt noire' },
    name: 'Bjorn Martelfer',
    gender: 'm',
    age: 52,
    title: { fr: 'Maître forgeron', en: 'Master Blacksmith' },
    body: 'Dverger',
    faction: 'artisans',
    place: 'forge',
    home: 'martelfer',
    schedule: 'artisan',
    traits: { o: 0.35, c: 0.9, e: 0.45, a: 0.35, n: 0.55 },
    speech: 'bourru, fier, parle du métal comme d’un être vivant, grogne avant de répondre',
    story: 'Meilleur forgeron de Spokaheim, a forgé les lames exposées à l’armurerie.',
    secret: 'Son fils Eirik est parti seul dans la Forêt noire il y a dix jours et n’est pas revenu ; Bjorn a honte de l’avoir chassé après une dispute.',
    wants: 'du bon minerai et des nouvelles de son fils Eirik',
    likes: ['le cuivre pur', 'le travail bien fait', 'la soupe d’Astrid'],
    dislikes: ['le métal de la fonderie de Gunnhild', 'les apprentis pressés', 'les épées rouillées'],
    relations: [
      { key: 'astrid', type: 'époux', note: 'l’aime sans savoir le dire' },
      { key: 'kari', type: 'apprentie', note: 'la trouve maladroite mais douée' },
      { key: 'gunnhild', type: 'rivalité', note: 'se disputent la qualité du métal' },
    ],
    services: ['contracts', 'saga'],
    contracts: 'forge',
  },
  {
    key: 'astrid',
    initialMood: { fear: 0.5, cause: 'Eirik n’est pas rentré' },
    name: 'Astrid Martelfer',
    gender: 'f',
    age: 49,
    title: { fr: 'Cuisinière impériale', en: 'Imperial Cook' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'kitchen',
    home: 'martelfer',
    schedule: 'artisan',
    traits: { o: 0.5, c: 0.7, e: 0.8, a: 0.85, n: 0.6 },
    speech: 'chaleureuse, maternelle, appelle les gens « mon petit », adore les ragots',
    story: 'Nourrit le château et la moitié de la ville. Connaît tous les secrets de cuisine et beaucoup d’autres.',
    secret: 'Elle envoie en cachette des provisions à Sten le vagabond, qui est son frère déchu.',
    wants: 'retrouver son fils Eirik et des ingrédients frais',
    likes: ['le miel', 'les compliments sur sa cuisine', 'les nouvelles fraîches'],
    dislikes: ['la viande avariée', 'qu’on parle mal de Bjorn'],
    relations: [
      { key: 'bjorn', type: 'épouse', note: 'le trouve trop dur avec leur fils' },
      { key: 'sten', type: 'frère caché', note: 'personne ne le sait' },
      { key: 'solveig', type: 'amie', note: 'échangent les ragots' },
    ],
    services: ['contracts', 'shop'],
    contracts: 'kitchen',
    shop: 'kitchen',
  },
  {
    key: 'kari',
    initialMood: { fear: 0.25, cause: 'elle se sent coupable pour Eirik' },
    name: 'Kari Copeaux',
    gender: 'f',
    age: 19,
    title: { fr: 'Apprentie forgeronne', en: 'Apprentice Smith' },
    body: 'Dverger',
    faction: 'artisans',
    place: 'forge',
    home: 'martelfer',
    schedule: 'apprentice',
    traits: { o: 0.85, c: 0.35, e: 0.75, a: 0.7, n: 0.5 },
    speech: 'rapide, s’excuse souvent, pose mille questions sur les aventures',
    story: 'Orpheline recueillie par les Martelfer. Rêve de partir à l’aventure plutôt que de battre le fer.',
    secret: 'Elle sait où Eirik voulait aller : chercher la lame perdue de son grand-père dans une crypte de la Forêt noire.',
    wants: 'qu’un Élu l’emmène voir le monde',
    likes: ['les histoires d’Élus', 'les étincelles', 'les baies'],
    dislikes: ['balayer la forge', 'qu’on l’appelle petite'],
    relations: [
      { key: 'bjorn', type: 'maître', note: 'le craint et l’admire' },
      { key: 'eirik', type: 'ami', note: 'se sent coupable de ne pas l’avoir suivi' },
    ],
    services: ['gossip'],
  },
  {
    key: 'gunnhild',
    name: 'Gunnhild Fondeuse',
    gender: 'f',
    age: 45,
    title: { fr: 'Maîtresse de la fonderie', en: 'Foundry Mistress' },
    body: 'Dverger',
    faction: 'artisans',
    place: 'foundry',
    home: 'gunnhild',
    schedule: 'artisan',
    traits: { o: 0.8, c: 0.8, e: 0.4, a: 0.25, n: 0.3 },
    speech: 'directe, chiffres et rendements, impatiente avec les « traditionalistes »',
    story: 'A conçu l’entrepôt et ses fours. Veut industrialiser Spokaheim.',
    secret: 'Elle a volé les plans d’un haut fourneau dvergr en quittant les Brumes.',
    wants: 'du charbon et du minerai en quantité, pour prouver que son acier vaut celui de Bjorn',
    likes: ['l’efficacité', 'les machines', 'le charbon sec'],
    dislikes: ['Bjorn et ses méthodes d’ancêtre', 'le gaspillage'],
    relations: [
      { key: 'bjorn', type: 'rivalité', note: 'le respecte en secret' },
      { key: 'orm', type: 'protection', note: 'veille sur lui comme sur un fils' },
    ],
    services: ['contracts', 'shop'],
    contracts: 'foundry',
    shop: 'foundry',
  },
  {
    key: 'orm',
    name: 'Orm le Porteur',
    gender: 'm',
    age: 33,
    title: { fr: "Manutentionnaire de l'entrepôt", en: 'Warehouse Hand' },
    body: 'Dverger',
    faction: 'artisans',
    place: 'foundry-store',
    home: 'orm',
    schedule: 'artisan',
    traits: { o: 0.3, c: 0.6, e: 0.55, a: 0.95, n: 0.25 },
    speech: 'simple, gentil, lent, parle des animaux qu’il a croisés',
    story: 'Fort comme trois bœufs, porte les caisses de minerai. Nourrit en cachette les sangliers apprivoisés.',
    secret: 'Il ne sait pas lire et a peur qu’on le découvre.',
    wants: 'un sanglier apprivoisé à lui',
    likes: ['les sangliers', 'les caisses bien rangées', 'les chansons simples'],
    dislikes: ['qu’on crie', 'les loups'],
    relations: [{ key: 'gunnhild', type: 'loyauté', note: 'ferait tout pour elle' }],
    services: ['gossip'],
  },
  {
    key: 'halla',
    initialMood: { fear: 0.25, cause: 'la poutre fendue du château' },
    name: 'Halla Charpente',
    gender: 'f',
    age: 56,
    title: { fr: 'Maîtresse bâtisseuse', en: 'Master Builder' },
    body: 'Dverger',
    faction: 'artisans',
    place: 'workshop',
    home: 'halla',
    schedule: 'artisan',
    traits: { o: 0.75, c: 0.85, e: 0.45, a: 0.4, n: 0.4 },
    speech: 'précise, parle en mesures et en poutres, critique les constructions des autres',
    story: 'Architecte de Spokaheim : les remparts, le château et la brasserie sont de sa main.',
    secret: 'Une poutre maîtresse du château est fendue ; elle cherche du bois dur pour la remplacer avant que ça se voie.',
    wants: 'du bois de cœur et du bois fin pour de nouveaux chantiers',
    likes: ['les charpentes solides', 'le bois de cœur', 'les plans bien tracés'],
    dislikes: ['les huttes de travers', 'les termites', 'la hâte'],
    relations: [
      { key: 'gunnhild', type: 'estime', note: 'collaborent sur les machines' },
      { key: 'hilda', type: 'tension', note: 'Hilda se plaint de chaque réparation' },
    ],
    services: ['contracts'],
    contracts: 'workshop',
  },
  {
    key: 'vigdis',
    name: 'Vigdis la Sage',
    gender: 'f',
    age: 71,
    title: { fr: 'Mage du Cercle', en: 'Circle Mage' },
    body: 'DvergerMageFire',
    faction: 'couronne',
    place: 'mage',
    home: 'vigdis',
    schedule: 'scholar',
    traits: { o: 0.95, c: 0.5, e: 0.35, a: 0.5, n: 0.45 },
    speech: 'énigmatique, digressions savantes, s’émerveille de tout ce qui est étrange',
    story: 'Étudie l’Eitr, les runes et la nature des Élus. Soupçonne que les Pierres sacrées sont plus anciennes que les dieux.',
    secret: 'Elle a lu dans les runes que l’un des Élus trahira la ville.',
    wants: 'des échantillons rares : œil de Greydwarf, résine, Eitr, cristal',
    likes: ['les runes', 'l’Eitr', 'les questions intelligentes'],
    dislikes: ['les ignorants sûrs d’eux', 'Hakon et son fanatisme'],
    relations: [
      { key: 'dagny', type: 'débat', note: 'discutent des dieux jusqu’à l’aube' },
      { key: 'thyra', type: 'élève', note: 'lui a appris les portails' },
    ],
    services: ['contracts', 'shop', 'lore'],
    contracts: 'mage',
    shop: 'mage',
  },
  {
    key: 'solveig',
    name: 'Solveig Hydromel',
    gender: 'f',
    age: 38,
    title: { fr: 'Tavernière de la Grande Brasserie', en: 'Innkeeper of the Great Mead Hall' },
    body: 'Dverger',
    faction: 'marchands',
    place: 'brasserie-bar',
    home: 'hydromel',
    schedule: 'tavern',
    traits: { o: 0.6, c: 0.65, e: 0.9, a: 0.7, n: 0.3 },
    speech: 'rieuse, taquine, sert des surnoms à tout le monde, connaît toutes les rumeurs',
    story: 'Tient la Grande Brasserie et le tableau des contrats. Personne ne part sans avoir payé sa tournée.',
    secret: 'Elle mouille l’hydromel les soirs d’affluence.',
    wants: 'des clients, des histoires et du miel pour Gorm',
    likes: ['les bonnes histoires', 'les pourboires', 'les soirs de fête'],
    dislikes: ['les bagarres', 'les ardoises impayées de Torvald'],
    relations: [
      { key: 'gorm', type: 'sœur', note: 'le couve et le gronde' },
      { key: 'astrid', type: 'amie', note: 'commères associées' },
      { key: 'leif', type: 'employeuse', note: 'le paie en hydromel' },
    ],
    services: ['shop', 'contracts', 'rumors'],
    contracts: 'tavern',
    shop: 'tavern',
  },
  {
    key: 'gorm',
    name: 'Gorm Cuvebrune',
    gender: 'm',
    age: 35,
    title: { fr: 'Maître brasseur', en: 'Master Brewer' },
    body: 'Dverger',
    faction: 'marchands',
    place: 'brasserie-brewery',
    home: 'hydromel',
    schedule: 'brewer',
    traits: { o: 0.9, c: 0.4, e: 0.75, a: 0.8, n: 0.35 },
    speech: 'jovial, parle de ses recettes comme de ses enfants, rit de ses propres ratés',
    story: 'Invente des hydromels étranges ; certains sont excellents, d’autres ont fait exploser une cuve.',
    secret: 'Sa recette d’hydromel « de l’Empereur » contient une champignon des marais qui rend un peu fou.',
    wants: 'du miel, des baies et des champignons pour ses nouvelles recettes',
    likes: ['le miel sauvage', 'les expériences', 'la fête'],
    dislikes: ['la bière sans goût', 'Hilda qui interdit ses dégustations'],
    relations: [
      { key: 'solveig', type: 'frère', note: 'lui obéit à moitié' },
      { key: 'torvald', type: 'créancier', note: 'Torvald lui doit 40 pièces' },
    ],
    services: ['contracts'],
    contracts: 'brewery',
  },
  {
    key: 'leif',
    name: 'Leif Chantevent',
    gender: 'm',
    age: 29,
    title: { fr: 'Barde', en: 'Bard' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'brasserie-stage',
    home: 'leif',
    schedule: 'bard',
    traits: { o: 0.9, c: 0.25, e: 0.9, a: 0.65, n: 0.4 },
    speech: 'lyrique, exagère tout, rime parfois, flatte les Élus pour obtenir des récits',
    story: 'Compose des sagas sur les exploits des Élus et les chante à la brasserie le soir.',
    secret: 'Il n’a jamais quitté les murs de la ville : toutes ses aventures sont inventées.',
    wants: 'de vraies histoires d’exploits à mettre en chanson',
    likes: ['les exploits', 'les applaudissements', 'Sigrun (sans le savoir)'],
    dislikes: ['le silence', 'les critiques', 'les chemins boueux'],
    relations: [
      { key: 'sigrun', type: 'amitié', note: 'ne voit pas qu’elle l’aime' },
      { key: 'solveig', type: 'patronne', note: 'lui doit sa scène' },
    ],
    services: ['songs', 'rumors'],
  },
  {
    key: 'dagny',
    name: 'Dagny Blanche-Rune',
    gender: 'f',
    age: 63,
    title: { fr: 'Prêtresse des Ases', en: 'Priestess of the Aesir' },
    body: 'DvergerMageSupport',
    faction: 'temple',
    place: 'church',
    home: 'dagny',
    schedule: 'priest',
    traits: { o: 0.7, c: 0.75, e: 0.5, a: 0.85, n: 0.25 },
    speech: 'sereine, parle par images et visions, bénit les voyageurs',
    story: 'Guide spirituelle de la ville, fait le sermon de l’aube. Ses rêves annoncent parfois ce qui arrive.',
    secret: 'Elle doute que les dieux écoutent encore, mais continue pour ne pas briser l’espoir de la ville.',
    wants: 'des offrandes pour les dieux et la paix dans la ville',
    likes: ['l’aube', 'les chants', 'les offrandes sincères'],
    dislikes: ['la violence gratuite', 'le fanatisme de Hakon'],
    relations: [
      { key: 'ingrid', type: 'confidente', note: 'connaît le secret de l’Empereur' },
      { key: 'hakon', type: 'acolyte', note: 'le trop zélé' },
      { key: 'vigdis', type: 'débat', note: 'foi contre savoir, avec affection' },
    ],
    services: ['contracts', 'blessing', 'saga'],
    contracts: 'temple',
  },
  {
    key: 'hakon',
    initialMood: { fear: 0.35, cause: 'son vol d’offrande pourrait être découvert' },
    name: "Hakon l'Acolyte",
    gender: 'm',
    age: 22,
    title: { fr: 'Acolyte du temple', en: 'Temple Acolyte' },
    body: 'Dverger',
    faction: 'temple',
    place: 'church-door',
    home: 'dagny',
    schedule: 'acolyte',
    traits: { o: 0.2, c: 0.8, e: 0.55, a: 0.35, n: 0.75 },
    speech: 'zélé, moralisateur, voit des signes partout, parle de péchés',
    story: 'Balaie le temple et surveille les « impies ». Rêve d’être choisi par les dieux.',
    secret: 'Il a volé une offrande d’or pour s’acheter une amulette, et vit dans la peur d’être découvert.',
    wants: 'qu’on respecte les rites',
    likes: ['les rites', 'les bougies', 'qu’on l’écoute'],
    dislikes: ['Vigdis', 'Torvald', 'les jurons'],
    relations: [{ key: 'dagny', type: 'vénération', note: 'veut lui succéder' }],
    services: ['gossip'],
  },
  {
    key: 'egil',
    name: 'Egil Garde-Mémoire',
    gender: 'm',
    age: 67,
    title: { fr: "Conservateur de l'armurerie", en: 'Curator of the Armory' },
    body: 'Dverger',
    faction: 'couronne',
    place: 'armory',
    home: 'egil',
    schedule: 'curator',
    traits: { o: 0.8, c: 0.95, e: 0.3, a: 0.5, n: 0.5 },
    speech: 'pédant, date et nomme chaque arme, corrige les erreurs historiques',
    story: 'Classe chaque arme et armure du royaume par terre d’origine. L’armurerie est sa vie.',
    secret: 'La couronne de Valheim exposée autrefois est une copie ; il a vendu l’originale pour sauver l’armurerie de la faillite.',
    wants: 'des trophées rares pour la salle des trophées',
    likes: ['les trophées', 'l’ordre alphabétique', 'le silence des salles'],
    dislikes: ['qu’on touche aux présentoirs', 'Ragna qui veut « emprunter » des armes'],
    relations: [{ key: 'ragna', type: 'méfiance', note: 'elle a déjà cassé une hache exposée' }],
    services: ['contracts', 'lore'],
    contracts: 'armory',
  },
  {
    key: 'ragna',
    name: 'Ragna Sang-Vif',
    gender: 'f',
    age: 34,
    title: { fr: "Maîtresse de l'arène", en: 'Arena Mistress' },
    body: 'Dverger',
    faction: 'garde',
    place: 'arena',
    home: 'ragna',
    schedule: 'arena',
    traits: { o: 0.6, c: 0.5, e: 0.95, a: 0.3, n: 0.2 },
    speech: 'provocatrice, lance des défis, rit fort, parle de gloire et de sang',
    story: 'Championne invaincue de l’arène. Organise les combats et tient le registre des records.',
    secret: 'Elle a perdu un combat en secret contre un Élu masqué et n’a jamais retrouvé qui c’était.',
    wants: 'des combattants dignes de ce nom dans l’arène',
    likes: ['la gloire', 'les paris', 'les cicatrices'],
    dislikes: ['Hrolf le vieux grincheux', 'les couards', 'les règles'],
    relations: [
      { key: 'hrolf', type: 'rivalité', note: 'se chamaillent depuis des années' },
      { key: 'torvald', type: 'parieur', note: 'il parie toujours contre elle et perd' },
    ],
    services: ['contracts', 'arena'],
    contracts: 'arena',
  },
  {
    key: 'thyra',
    initialMood: { sadness: 0.4, cause: 'sa sœur asservie dans les Brumes' },
    name: 'Thyra Voile-Brume',
    gender: 'f',
    age: 40,
    title: { fr: 'Gardienne des portails', en: 'Keeper of the Portals' },
    body: 'DvergerMage',
    faction: 'couronne',
    place: 'portals',
    home: 'thyra',
    schedule: 'keeper',
    traits: { o: 0.9, c: 0.6, e: 0.3, a: 0.55, n: 0.5 },
    speech: 'lente, mystérieuse, parle des terres lointaines comme si elle les voyait',
    story: 'Veille sur la place des portails et renseigne les voyageurs sur les terres de Valheim.',
    secret: 'Elle a traversé un portail vers les Brumes et y a vu sa sœur, asservie par la Reine.',
    wants: 'que des Élus explorent les terres lointaines et lui rapportent ce qu’ils y voient',
    likes: ['les cartes', 'les récits d’exploration', 'le brouillard'],
    dislikes: ['les portails mal nommés', 'Ulfar qui la croit maudite'],
    relations: [
      { key: 'vigdis', type: 'mentor', note: 'lui doit son savoir' },
      { key: 'ulfar', type: 'méfiance réciproque', note: 'il la croit porteuse de malheur' },
    ],
    services: ['contracts', 'lore'],
    contracts: 'explore',
  },
  {
    key: 'ragnhild',
    name: 'Ragnhild la Marchande',
    gender: 'f',
    age: 47,
    title: { fr: 'Marchande du marché couvert', en: 'Covered Market Trader' },
    body: 'Dverger',
    faction: 'marchands',
    place: 'market',
    home: 'ragnhild',
    schedule: 'merchant',
    traits: { o: 0.55, c: 0.75, e: 0.7, a: 0.35, n: 0.35 },
    speech: 'rusée, marchande tout, compte à voix haute, flatte les clients fortunés',
    story: 'Achète et revend tout ce qui passe par Spokaheim. Connaît le prix de chaque chose et de chacun.',
    secret: 'Elle achète des objets volés sans poser de questions.',
    wants: 'faire des affaires, surtout sur les matériaux rares',
    likes: ['l’or', 'les bonnes affaires', 'Haldor (son concurrent qu’elle admire)'],
    dislikes: ['les voleurs qui ne partagent pas', 'les prix fixes'],
    relations: [
      { key: 'bodil', type: 'voisine', note: 'partagent la halle' },
      { key: 'sten', type: 'indicateur', note: 'lui achète des informations' },
    ],
    services: ['shop', 'contracts'],
    contracts: 'merchant',
    shop: 'market',
  },
  {
    key: 'bodil',
    initialMood: { sadness: 0.2, cause: 'son mari mort face aux trolls' },
    name: 'Bodil Pain-Doré',
    gender: 'f',
    age: 36,
    title: { fr: 'Boulangère et maraîchère', en: 'Baker and Greengrocer' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'market-food',
    home: 'bodil',
    schedule: 'merchant',
    traits: { o: 0.45, c: 0.7, e: 0.8, a: 0.9, n: 0.4 },
    speech: 'joyeuse, vante ses pains, parle de ses deux enfants à tout le monde',
    story: 'Vend pain, légumes et confitures au marché couvert. Veuve depuis la dernière attaque de trolls.',
    secret: 'Elle a un faible pour Hrolf le capitaine.',
    wants: 'de l’orge, des carottes et du miel pour ses fournées',
    likes: ['l’odeur du pain', 'les enfants', 'les fleurs des prairies'],
    dislikes: ['les trolls', 'la farine humide'],
    relations: [
      { key: 'hrolf', type: 'béguin', note: 'lui garde toujours le meilleur pain' },
      { key: 'frida', type: 'fournisseuse', note: 'lui achète ses légumes' },
    ],
    services: ['shop', 'contracts'],
    contracts: 'baker',
    shop: 'bakery',
  },
  {
    key: 'arne',
    name: 'Arne Crieur',
    gender: 'm',
    age: 44,
    title: { fr: 'Crieur public', en: 'Town Crier' },
    body: 'Dverger',
    faction: 'couronne',
    place: 'plaza-crier',
    home: 'arne',
    schedule: 'crier',
    traits: { o: 0.4, c: 0.7, e: 0.95, a: 0.5, n: 0.3 },
    speech: 'pompeux, emphatique, commence ses phrases par « Oyez ! », adore les titres ronflants',
    story: 'Annonce les proclamations de l’Empereur et les exploits des Élus sur la grand-place.',
    secret: 'Il invente parfois des nouvelles quand il n’y en a pas.',
    wants: 'des exploits à annoncer',
    likes: ['sa propre voix', 'les titres', 'les foules'],
    dislikes: ['qu’on l’interrompe', 'les jours sans nouvelles'],
    relations: [{ key: 'leif', type: 'concurrence', note: 'se disputent le récit des exploits' }],
    services: ['news'],
  },
  {
    key: 'frida',
    name: 'Frida Champs-Verts',
    gender: 'f',
    age: 42,
    title: { fr: 'Paysanne', en: 'Farmer' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'garden',
    home: 'champsverts',
    schedule: 'farmer',
    traits: { o: 0.3, c: 0.9, e: 0.5, a: 0.6, n: 0.55 },
    speech: 'terre à terre, se plaint du temps et des sangliers, proverbes paysans',
    story: 'Cultive les jardins de la ville et les champs hors des murs. Nourrit la ville avec Bodil.',
    secret: 'Elle garde des graines de navet des anciens temps, que tout le monde croit perdues.',
    wants: 'qu’on chasse les sangliers et les nécks qui ravagent ses cultures',
    likes: ['la pluie fine', 'les carottes', 'les journées longues'],
    dislikes: ['les sangliers', 'la paresse d’Olaf'],
    relations: [
      { key: 'olaf', type: 'épouse', note: 'l’aime mais le secoue' },
      { key: 'bodil', type: 'cliente', note: 'sa meilleure acheteuse' },
    ],
    services: ['contracts'],
    contracts: 'farm',
  },
  {
    key: 'olaf',
    name: 'Olaf Champs-Verts',
    gender: 'm',
    age: 47,
    title: { fr: 'Paysan', en: 'Farmer' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'garden',
    home: 'champsverts',
    schedule: 'lazy-farmer',
    traits: { o: 0.75, c: 0.2, e: 0.45, a: 0.8, n: 0.2 },
    speech: 'philosophe, lent, pose des questions sur le sens de la vie, sieste facile',
    story: 'Mari de Frida. Préfère regarder pousser les navets que les planter.',
    secret: 'Il écrit des poèmes et les cache sous le lit.',
    wants: 'une bonne sieste et une vraie conversation',
    likes: ['l’ombre', 'les questions profondes', 'l’hydromel tiède'],
    dislikes: ['se lever tôt', 'les sangliers (surtout parce que Frida en parle)'],
    relations: [
      { key: 'frida', type: 'époux', note: 'l’admire' },
      { key: 'leif', type: 'ami', note: 'lui montre parfois ses poèmes' },
    ],
    services: ['gossip'],
  },
  {
    key: 'ivar',
    name: 'Ivar Pistetrouble',
    gender: 'm',
    age: 39,
    title: { fr: 'Chasseur', en: 'Hunter' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'gate0',
    placeKind: 'outskirts',
    home: 'ivar',
    schedule: 'hunter',
    traits: { o: 0.5, c: 0.65, e: 0.2, a: 0.4, n: 0.35 },
    speech: 'laconique, parle des traces et des bêtes, méprise les bruyants',
    story: 'Chasse aux abords de la ville et vend peaux et viande. Connaît chaque bête de Valheim.',
    secret: 'Il a apprivoisé un loup qu’il cache dans les bois.',
    wants: 'des chasseurs capables pour réguler les bêtes dangereuses',
    likes: ['la forêt au matin', 'les arcs bien tendus', 'le silence'],
    dislikes: ['les bruyants', 'le gaspillage de viande'],
    relations: [{ key: 'orm', type: 'amitié', note: 'partagent l’amour des bêtes' }],
    services: ['contracts'],
    contracts: 'hunt',
  },
  {
    key: 'brynja',
    name: "Brynja Filet-d'Argent",
    gender: 'f',
    age: 51,
    title: { fr: 'Pêcheuse', en: 'Fisherwoman' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'gate180',
    placeKind: 'outskirts',
    home: 'brynja',
    schedule: 'fisher',
    traits: { o: 0.5, c: 0.55, e: 0.7, a: 0.5, n: 0.3 },
    speech: 'humour salé, jure comme un marin, compare tout à des poissons',
    story: 'Pêche dans les douves et la mer voisine. A navigué jusqu’aux côtes des Terres cendrées.',
    secret: 'Elle a vu le Serpent de mer et a fui en abandonnant son équipage.',
    wants: 'des poissons rares et quelqu’un pour chasser les serpents de mer',
    likes: ['la mer', 'le poisson frit', 'les tempêtes vues de loin'],
    dislikes: ['les serpents de mer', 'les marins d’eau douce'],
    relations: [{ key: 'gorm', type: 'compagne de beuverie', note: 'boivent ensemble' }],
    services: ['contracts'],
    contracts: 'fish',
  },
  {
    key: 'yrsa',
    name: 'Yrsa Herbe-Douce',
    gender: 'f',
    age: 55,
    title: { fr: 'Herboriste', en: 'Herbalist' },
    body: 'DvergerMageSupport',
    faction: 'temple',
    place: 'kitchen',
    home: 'yrsa',
    schedule: 'herbalist',
    traits: { o: 0.7, c: 0.6, e: 0.35, a: 0.7, n: 0.5 },
    speech: 'douce, précise sur les plantes, murmure, donne des conseils de santé',
    story: 'Soigne les blessés et prépare remèdes et hydromels de guérison.',
    secret: 'Dans sa jeunesse, elle a empoisonné un seigneur cruel des Brumes.',
    wants: 'des chardons, des pissenlits, des champignons et du miel pour ses remèdes',
    likes: ['les chardons bleus', 'les tisanes', 'le calme'],
    dislikes: ['les blessures négligées', 'les champignons toxiques mal rangés'],
    relations: [
      { key: 'dagny', type: 'alliée', note: 'soignent ensemble corps et âmes' },
      { key: 'astrid', type: 'voisine de cuisine', note: 'se disputent la place au feu' },
    ],
    services: ['contracts', 'shop'],
    contracts: 'herbs',
    shop: 'herbs',
  },
  {
    key: 'sten',
    name: 'Sten le Vagabond',
    gender: 'm',
    age: 57,
    title: { fr: 'Vagabond', en: 'Vagrant' },
    body: 'Dverger',
    faction: 'peuple',
    place: 'plaza',
    home: 'church-door',
    schedule: 'vagrant',
    traits: { o: 0.85, c: 0.15, e: 0.5, a: 0.45, n: 0.7 },
    speech: 'cryptique, ironique, demande une pièce, lâche des secrets à demi-mot',
    story: 'Mendie sur la grand-place. Semble savoir des choses qu’un mendiant ne devrait pas savoir.',
    secret: 'Ancien seigneur ruiné et frère d’Astrid ; il connaît le passage secret sous le château.',
    wants: 'une pièce, un repas, et qu’on l’écoute',
    likes: ['l’hydromel', 'les pièces', 'les secrets'],
    dislikes: ['Hakon', 'les gardes', 'la pitié'],
    relations: [
      { key: 'astrid', type: 'sœur cachée', note: 'la seule qui le nourrit' },
      { key: 'ragnhild', type: 'informateur', note: 'lui vend des rumeurs' },
    ],
    services: ['rumors', 'contracts'],
    contracts: 'vagrant',
  },
];

// Personnages évoqués mais absents au départ (la saga peut les faire revenir).
export const ABSENT = [
  {
    key: 'eirik',
    name: 'Eirik Martelfer',
    gender: 'm',
    age: 21,
    title: { fr: 'Fils du forgeron', en: "Blacksmith's son" },
    body: 'Dverger',
    faction: 'artisans',
    place: 'forge',
    home: 'martelfer',
    schedule: 'apprentice',
    traits: { o: 0.8, c: 0.4, e: 0.6, a: 0.6, n: 0.5 },
    speech: 'fougueux, reconnaissant, veut prouver sa valeur à son père',
    story: 'Parti chercher la lame de son grand-père dans une crypte de la Forêt noire. Sauvé par un Élu.',
    secret: 'Il a trouvé dans la crypte une rune qui parle de la Reine des Brumes.',
    wants: 'se réconcilier avec son père',
    likes: ['les lames anciennes', 'Kari'],
    dislikes: ['les squelettes', 'la morgue de son père'],
    relations: [
      { key: 'bjorn', type: 'fils', note: 'en froid' },
      { key: 'kari', type: 'amitié', note: 'plus que de l’amitié ?' },
    ],
    services: ['gossip'],
  },
];
